name: Convert MLML templates to HTML templates

on: [push]

jobs:
  run:
    runs-on: ubuntu-18.04
#    strategy:
#      matrix:
#        input: [templates]
#        output: [dist]

    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Compile
      - uses: W0lfw00d/mjml-github-action@0.0.2

        with:
            input_dir: 'templates'
            output_dir: 'dist'
#        with:
#          input: ${{matrix.input}}
#          output: ${{matrix.output}}
